-- Down for 20261005161732_diletta: drops the 28 tables it created (no foreign keys, so order doesn't matter).
DROP TABLE "activity_log";--> statement-breakpoint
DROP TABLE "activity_rollups";--> statement-breakpoint
DROP TABLE "admins";--> statement-breakpoint
DROP TABLE "change_requests";--> statement-breakpoint
DROP TABLE "chatbot_configs";--> statement-breakpoint
DROP TABLE "chatbot_user_secrets";--> statement-breakpoint
DROP TABLE "chatbot_users";--> statement-breakpoint
DROP TABLE "company_connections";--> statement-breakpoint
DROP TABLE "company_encryption_keys";--> statement-breakpoint
DROP TABLE "company_secrets";--> statement-breakpoint
DROP TABLE "conversations";--> statement-breakpoint
DROP TABLE "doc_gap_clusters";--> statement-breakpoint
DROP TABLE "doc_gaps";--> statement-breakpoint
DROP TABLE "eval_cases";--> statement-breakpoint
DROP TABLE "eval_results";--> statement-breakpoint
DROP TABLE "eval_runs";--> statement-breakpoint
DROP TABLE "event_outbox";--> statement-breakpoint
DROP TABLE "feedback";--> statement-breakpoint
DROP TABLE "files";--> statement-breakpoint
DROP TABLE "knowledge_chunks";--> statement-breakpoint
DROP TABLE "knowledge_documents";--> statement-breakpoint
DROP TABLE "knowledge_sources";--> statement-breakpoint
DROP TABLE "messages";--> statement-breakpoint
DROP TABLE "model_calls";--> statement-breakpoint
DROP TABLE "quality_issues";--> statement-breakpoint
DROP TABLE "roi_assumptions";--> statement-breakpoint
DROP TABLE "tool_calls";--> statement-breakpoint
DROP TABLE "tool_definitions";
